### ISSUE TITLE
exception when opening external file

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#108]
It happens every time I change focus to the editor where external file(not in workspace) is 
opened, no matter what is the contents of the external file.

eclipse.buildId=4.6.1.M20160907-1200
java.version=1.8.0_74
java.vendor=Oracle Corporation
BootLoader constants: OS=linux, ARCH=x86_64, WS=gtk, NL=en_US
Framework arguments:  -product org.eclipse.epp.package.cpp.product -showlocation
Command-line arguments:  -os linux -ws gtk -arch x86_64 -product org.eclipse.epp.package.cpp.product -showlocation -data /local/scratch/xelevol/ws_wd1_ibm_daily_neon

org.eclipse.ui.workbench
Error
Mon Jan 30 08:31:06 CET 2017
Problems occurred when invoking code from plug-in: "org.eclipse.ui.workbench".

java.lang.ClassCastException: org.eclipse.ui.ide.FileStoreEditorInput cannot be cast to org.eclipse.ui.IFileEditorInput
               at cc.codechecker.plugin.config.CodeCheckerContext.refreshChangeEditorPart(CodeCheckerContext.java:270)
               at cc.codechecker.plugin.init.EditorPartListener.partActivated(EditorPartListener.java:19)
               at org.eclipse.ui.internal.WorkbenchPage$14.run(WorkbenchPage.java:4977)
               at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
               at org.eclipse.ui.internal.WorkbenchPage.firePartActivated(WorkbenchPage.java:4974)
               at org.eclipse.ui.internal.WorkbenchPage.access$19(WorkbenchPage.java:4962)
               at org.eclipse.ui.internal.WorkbenchPage$E4PartListener.partActivated(WorkbenchPage.java:210)
               at org.eclipse.e4.ui.internal.workbench.PartServiceImpl$3.run(PartServiceImpl.java:250)
               at org.eclipse.core.runtime.SafeRunner.run(SafeRunner.java:42)
               at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.firePartActivated(PartServiceImpl.java:247)
               at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:757)
               at org.eclipse.e4.ui.internal.workbench.PartServiceImpl.activate(PartServiceImpl.java:682)
               at org.eclipse.e4.ui.internal.workbench.swt.AbstractPartRenderer.activate(AbstractPartRenderer.java:95)
               at org.eclipse.e4.ui.workbench.renderers.swt.ContributedPartRenderer$1.handleEvent(ContributedPartRenderer.java:63)
               at org.eclipse.swt.widgets.EventTable.sendEvent(EventTable.java:84)
               at org.eclipse.swt.widgets.Display.sendEvent(Display.java:5219)
               at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1340)
               at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1366)
               at org.eclipse.swt.widgets.Widget.sendEvent(Widget.java:1349)
               at org.eclipse.swt.widgets.Shell.setActiveControl(Shell.java:1817)
               at org.eclipse.swt.widgets.Control.gtk_button_press_event(Control.java:3215)
               at org.eclipse.swt.widgets.Control.gtk_button_press_event(Control.java:3151)
               at org.eclipse.swt.widgets.Composite.gtk_button_press_event(Composite.java:750)
               at org.eclipse.swt.widgets.Canvas.gtk_button_press_event(Canvas.java:155)
               at org.eclipse.swt.widgets.Widget.windowProc(Widget.java:1979)
               at org.eclipse.swt.widgets.Control.windowProc(Control.java:5819)
               at org.eclipse.swt.widgets.Display.windowProc(Display.java:5490)
               at org.eclipse.swt.internal.gtk.OS._gtk_main_do_event(Native Method)
               at org.eclipse.swt.internal.gtk.OS.gtk_main_do_event(OS.java:9555)
               at org.eclipse.swt.widgets.Display.eventProc(Display.java:1275)
               at org.eclipse.swt.internal.gtk.OS._g_main_context_iteration(Native Method)
               at org.eclipse.swt.internal.gtk.OS.g_main_context_iteration(OS.java:2495)
               at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:4141)
               at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine$4.run(PartRenderingEngine.java:1121)
               at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
               at org.eclipse.e4.ui.internal.workbench.swt.PartRenderingEngine.run(PartRenderingEngine.java:1022)
               at org.eclipse.e4.ui.internal.workbench.E4Workbench.createAndRunUI(E4Workbench.java:150)
               at org.eclipse.ui.internal.Workbench$5.run(Workbench.java:687)
               at org.eclipse.core.databinding.observable.Realm.runWithDefault(Realm.java:336)
               at org.eclipse.ui.internal.Workbench.createAndRunWorkbench(Workbench.java:604)
               at org.eclipse.ui.PlatformUI.createAndRunWorkbench(PlatformUI.java:148)
               at org.eclipse.ui.internal.ide.application.IDEApplication.start(IDEApplication.java:138)
               at org.eclipse.equinox.internal.app.EclipseAppHandle.run(EclipseAppHandle.java:196)
               at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.runApplication(EclipseAppLauncher.java:134)
               at org.eclipse.core.runtime.internal.adaptor.EclipseAppLauncher.start(EclipseAppLauncher.java:104)
               at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:388)
               at org.eclipse.core.runtime.adaptor.EclipseStarter.run(EclipseStarter.java:243)
               at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
               at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
               at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
               at java.lang.reflect.Method.invoke(Method.java:498)
               at org.eclipse.equinox.launcher.Main.invokeFramework(Main.java:673)
               at org.eclipse.equinox.launcher.Main.basicRun(Main.java:610)
               at org.eclipse.equinox.launcher.Main.run(Main.java:1519)
               at org.eclipse.equinox.launcher.Main.main(Main.java:1492)

**Comment by dkrupp** [comment]
duplicate of #105
