### ISSUE TITLE
exception is thrown when eclipse is closed

### ISSUE THREAD

**Issue by dkrupp** [Ericsson/CodeCheckerEclipsePlugin#40]

**Comment by Locutus18** [comment]
Exception is thrown message when eclipse is stopped : 

```
2016-07-20 Thread-10  ERROR CodecheckerServerThread:90 - SERVER_SER_MSG >> java.lang.InterruptedException
org.apache.commons.exec.ExecuteException: Process exited with an error: -559038737 (Exit value: -559038737)
	at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
	at org.apache.commons.exec.DefaultExecutor.execute(DefaultExecutor.java:166)
	at cc.codechecker.api.runtime.ShellExecutorHelper$Executable.start(ShellExecutorHelper.java:174)
	at cc.codechecker.api.runtime.CodecheckerServerThread$1.run(CodecheckerServerThread.java:61)
	at java.lang.Thread.run(Thread.java:745)

2016-07-20 Thread-9  ERROR ShellExecutorHelper:177 - SERVER_SER_MSG >> org.apache.commons.exec.ExecuteException: Process exited with an error: -559038737 (Exit value: -559038737)
java.lang.InterruptedException
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.reportInterruptAfterWait(AbstractQueuedSynchronizer.java:2014)
    at java.util.concurrent.locks.AbstractQueuedSynchronizer$ConditionObject.await(AbstractQueuedSynchronizer.java:2048)
    at java.util.concurrent.LinkedBlockingDeque.takeFirst(LinkedBlockingDeque.java:492)
    at java.util.concurrent.LinkedBlockingDeque.take(LinkedBlockingDeque.java:680)
    at cc.codechecker.api.runtime.CodecheckerServerThread$2.run(CodecheckerServerThread.java:79)
	at java.lang.Thread.run(Thread.java:745)
```

And kill the thread script : 

```
list_descendants () { 
    local children=$(ps -o pid= --ppid "$1"); 
    for pid in $children;   do 
            list_descendants "$pid"; 
    done; 
    echo "$children";
 }; 
kill $(list_descendants 12584)
```
